# version: "3"

services:
  magicmirror:
    container_name: mm
    build: .
    volumes:
      - ../mounts/config:/opt/magic_mirror/config
      - ../mounts/modules:/opt/magic_mirror/modules:rw
      - ../mounts/css:/opt/magic_mirror/css
      - ./runtime-start.sh:/opt/magic_mirror/runtime-start.sh
    privileged: true # avoids dbus errors in logs
    devices:
      - /dev/vchiq
    environment:
      DISPLAY: unix$DISPLAY
    network_mode: host
    shm_size: "128mb"
    restart: unless-stopped
